export default [
	"Datawrapper",
	"Vercel",
	"Cohere",
	"Dabble",
	"Frontend Masters",
	"Monogram",
	"PQINA",
	"Raster",
	"Avast",
	"Hugging Face",
	"INVISR",
	"Matt",
	"Layer0",
	"Metafy",
	"Threema Open Source Fund",
	"Changelog",
	"Clancy Digital",
	"Kenoxa GmbH",
	"Level Up Tutorials",
	"The Pudding",
	"Jason Hetherington",
	"Zev Averbach",
	"Donovan Dikaio",
	"multi"
];